<a href="https://colab.research.google.com/github/paolapeiz/Telemetria_Videojuegos/blob/main/TelemetriaVideojuegos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import pandas as pd

df = pd.read_csv('videojuegos_online_telemetria.csv')
display(df.head())

,PlayerID,Age,Region,Platform,PreferredGenre,SessionsPerWeek,AvgSessionMinutes,DaysSinceLastLogin,PlayerLevel,MatchesPlayedLast30D,WinRate,InGamePurchase,FriendsInGame,UsesVoiceChat,AchievementsUnlocked,ReportsReceivedLast30D,Churn30D
0,P0001,22.0,LATAM,PC,RPG,3,87.0,11,59,14,0.481,7.38,3.0,1,17,0,0
1,P0002,21.0,EU,PC,Shooter,7,113.0,0,45,24,0.475,11.56,8.0,1,21,2,0
2,P0003,40.0,LATAM,Mobile,Shooter,3,67.0,3,68,27,0.341,0.42,6.0,1,26,1,0
3,P0004,37.0,NaN,PC,Shooter,0,48.0,9,40,39,0.225,8.83,NaN,1,41,2,0
4,P0005,28.0,EU,Console,Shooter,3,90.0,15,51,15,0.454,23.86,0.0,0,35,1,1

In [44]:
print(f"Dimensiones del DataFrame antes de eliminar duplicados por PlayerID: {df.shape}")

df.drop_duplicates(subset=['PlayerID'], inplace=True)

print(f"Dimensiones del DataFrame después de eliminar duplicados por PlayerID: {df.shape}")

Dimensiones del DataFrame antes de eliminar duplicados por PlayerID: (558, 17)
Dimensiones del DataFrame después de eliminar duplicados por PlayerID: (550, 17)

In [45]:
min_age = df['Age'].min()
max_age = df['Age'].max()

print(f"Edad mínima de los jugadores: {min_age}")
print(f"Edad máxima de los jugadores: {max_age}")

Edad mínima de los jugadores: 16.0
Edad máxima de los jugadores: 40.0

In [46]:
# Reemplazar 'Europe' por 'EU'
df['Region'] = df['Region'].replace('Europe', 'EU')

# Rellenar valores NaN con 'EEUU'
df['Region'] = df['Region'].fillna('EEUU')

print("Valores distintos y su conteo en la columna 'Region' después de las transformaciones:")
display(df['Region'].value_counts(dropna=False))

Valores distintos y su conteo en la columna 'Region' después de las transformaciones:

Region
EU       265
EEUU     129
APAC      81
LATAM     75
Name: count, dtype: int64

In [47]:
print("Valores nulos por columna:")
display(df.isnull().sum())

Valores nulos por columna:

PlayerID                   0
Age                       12
Region                     0
Platform                   0
PreferredGenre             0
SessionsPerWeek            0
AvgSessionMinutes         12
DaysSinceLastLogin         0
PlayerLevel                0
MatchesPlayedLast30D       0
WinRate                   12
InGamePurchase            12
FriendsInGame             12
UsesVoiceChat              0
AchievementsUnlocked       0
ReportsReceivedLast30D     0
Churn30D                   0
dtype: int64

### Estandarización de mayúsculas/minúsculas en columnas de texto

Vamos a estandarizar las columnas de tipo 'object' (texto) convirtiendo todos sus valores a minúsculas. Esto unificará entradas que son iguales pero tienen diferentes capitalizaciones.

In [48]:
object_cols = df.select_dtypes(include='object').columns

print("Columnas de tipo 'object' a estandarizar:", object_cols.tolist())

for col in object_cols:
    # Solo aplicar si la columna no es 'PlayerID', ya que los IDs suelen ser case-sensitive y no necesitan estandarización de casing
    if col != 'PlayerID':
        if df[col].apply(lambda x: isinstance(x, str)).any(): # Ensure there are string values to process
            print(f"\nValores únicos en la columna '{col}' ANTES de la estandarización:")
            display(df[col].value_counts(dropna=False))
            df[col] = df[col].astype(str).str.lower()
            print(f"Valores únicos en la columna '{col}' DESPUÉS de la estandarización:")
            display(df[col].value_counts(dropna=False))

Columnas de tipo 'object' a estandarizar: ['PlayerID', 'Region', 'Platform', 'PreferredGenre']

Valores únicos en la columna 'Region' ANTES de la estandarización:

Region
EU       265
EEUU     129
APAC      81
LATAM     75
Name: count, dtype: int64

Valores únicos en la columna 'Region' DESPUÉS de la estandarización:

Region
eu       265
eeuu     129
apac      81
latam     75
Name: count, dtype: int64

Valores únicos en la columna 'Platform' ANTES de la estandarización:

Platform
PC         222
Console    158
Mobile     104
pc          66
Name: count, dtype: int64

Valores únicos en la columna 'Platform' DESPUÉS de la estandarización:

Platform
pc         288
console    158
mobile     104
Name: count, dtype: int64

Valores únicos en la columna 'PreferredGenre' ANTES de la estandarización:

PreferredGenre
Battle Royale    100
Strategy          93
Sports            93
RPG               92
MOBA              87
Shooter           85
Name: count, dtype: int64

Valores únicos en la columna 'PreferredGenre' DESPUÉS de la estandarización:

PreferredGenre
battle royale    100
strategy          93
sports            93
rpg               92
moba              87
shooter           85
Name: count, dtype: int64

In [49]:
columns_to_impute = ['AvgSessionMinutes', 'WinRate', 'InGamePurchase', 'FriendsInGame']

for col in columns_to_impute:
    if df[col].isnull().any():
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)
        print(f"Columna '{col}': valores nulos rellenados con la media ({mean_value:.2f})")

print("\nValores nulos por columna después de la imputación:")
display(df.isnull().sum())

Columna 'AvgSessionMinutes': valores nulos rellenados con la media (78.39)
Columna 'WinRate': valores nulos rellenados con la media (0.51)
Columna 'InGamePurchase': valores nulos rellenados con la media (14.38)
Columna 'FriendsInGame': valores nulos rellenados con la media (7.59)

Valores nulos por columna después de la imputación:

PlayerID                   0
Age                       12
Region                     0
Platform                   0
PreferredGenre             0
SessionsPerWeek            0
AvgSessionMinutes          0
DaysSinceLastLogin         0
PlayerLevel                0
MatchesPlayedLast30D       0
WinRate                    0
InGamePurchase             0
FriendsInGame              0
UsesVoiceChat              0
AchievementsUnlocked       0
ReportsReceivedLast30D     0
Churn30D                   0
dtype: int64